# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/config_mpsoc/config_mpsoc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==config_mpsoc || ORIG_REF_NAME==config_mpsoc} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_zynq_ultra_ps_e_0_1/config_mpsoc_zynq_ultra_ps_e_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==config_mpsoc_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==config_mpsoc_zynq_ultra_ps_e_0_1} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_axi_dma_0_0/config_mpsoc_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==config_mpsoc_axi_dma_0_0 || ORIG_REF_NAME==config_mpsoc_axi_dma_0_0} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_axi_smc_0/config_mpsoc_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==config_mpsoc_axi_smc_0 || ORIG_REF_NAME==config_mpsoc_axi_smc_0} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_rst_ps8_0_99M_1/config_mpsoc_rst_ps8_0_99M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==config_mpsoc_rst_ps8_0_99M_1 || ORIG_REF_NAME==config_mpsoc_rst_ps8_0_99M_1} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_ps8_0_axi_periph_1/config_mpsoc_ps8_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==config_mpsoc_ps8_0_axi_periph_1 || ORIG_REF_NAME==config_mpsoc_ps8_0_axi_periph_1} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_axis_data_fifo_0_0/config_mpsoc_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==config_mpsoc_axis_data_fifo_0_0 || ORIG_REF_NAME==config_mpsoc_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_xlconcat_0_0/config_mpsoc_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==config_mpsoc_xlconcat_0_0 || ORIG_REF_NAME==config_mpsoc_xlconcat_0_0} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_auto_ds_0_1/config_mpsoc_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==config_mpsoc_auto_ds_0 || ORIG_REF_NAME==config_mpsoc_auto_ds_0} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_auto_pc_0_1/config_mpsoc_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==config_mpsoc_auto_pc_0 || ORIG_REF_NAME==config_mpsoc_auto_pc_0} -quiet] -quiet

# XDC: bd/config_mpsoc/config_mpsoc_ooc.xdc
