# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/prodrigu/git/simpleNeuralNetwork/Vivado/NNA/NNA.srcs/sources_1/bd/config_mpsoc/ip/config_mpsoc_zynq_ultra_ps_e_0_1/config_mpsoc_zynq_ultra_ps_e_0_1.xci
# IP: The module: 'config_mpsoc_zynq_ultra_ps_e_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/prodrigu/git/simpleNeuralNetwork/Vivado/NNA/NNA.srcs/sources_1/bd/config_mpsoc/ip/config_mpsoc_zynq_ultra_ps_e_0_1/config_mpsoc_zynq_ultra_ps_e_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'config_mpsoc_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/prodrigu/git/simpleNeuralNetwork/Vivado/NNA/NNA.srcs/sources_1/bd/config_mpsoc/ip/config_mpsoc_zynq_ultra_ps_e_0_1/config_mpsoc_zynq_ultra_ps_e_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'config_mpsoc_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/prodrigu/git/simpleNeuralNetwork/Vivado/NNA/NNA.srcs/sources_1/bd/config_mpsoc/ip/config_mpsoc_zynq_ultra_ps_e_0_1/config_mpsoc_zynq_ultra_ps_e_0_1.xci
# IP: The module: 'config_mpsoc_zynq_ultra_ps_e_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/prodrigu/git/simpleNeuralNetwork/Vivado/NNA/NNA.srcs/sources_1/bd/config_mpsoc/ip/config_mpsoc_zynq_ultra_ps_e_0_1/config_mpsoc_zynq_ultra_ps_e_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'config_mpsoc_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/prodrigu/git/simpleNeuralNetwork/Vivado/NNA/NNA.srcs/sources_1/bd/config_mpsoc/ip/config_mpsoc_zynq_ultra_ps_e_0_1/config_mpsoc_zynq_ultra_ps_e_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'config_mpsoc_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
